Run infobar_deprecation_test.py on Python 3 _only_
infobar_deprecation_test.py was switched to Python 3 quite a while ago
but running it under Python 2 was never turned off. So, it ran twice!
The Python 2 runs always failed with this error:

  ImportError: No module named pathlib

This change uses "run_on_python2=False" to switch off Python 2.

At the same time I deleted USE_PYTHON3 = True from
infobar_deprecation.py because this magic incantation is only
significant inside PRESUBMIT.py files.

Bug: 1309977
Change-Id: I79011a5c1a015a59c7941ac417a38e25f67a960d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3789870
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1029247}
NOKEYCHECK=True
GitOrigin-RevId: a20d403ace73ee8eed0a44c85bd46a88491f4a12