Reland "[Settings] Add settings file name presubmit"
This reverts commit 595272f36e94f0efc4916ca6e1a7fa7c978b9539.

Reason for revert: Do not use negative look ahead that's not supported by checkstyle.

Original change's description:
> Revert "[Settings] Add settings file name presubmit"
>
> This reverts commit 5097e3556e89bc457880a5f6a5fe22426cf0ffaf.
>
> Reason for revert: PRESUBMIT fails:
>
> ```
> Running Python 3 presubmit upload checks ...
>   18.1s to run CheckUnwantedDependencies from /usr/local/google/home/kdlee/chromium/src/PRESUBMIT.py.
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The value of attribute "value" associated with an element type "property" must not contain the '<' character.:226:57
>         at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:321)
>         ...
> Checkstyle ends with 1 errors.
> ```
>
> Original change's description:
> > [Settings] Add settings file name presubmit
> >
> > Prevent new class added with suffix "PreferenceFragment". Regex tested through https://screenshot.googleplex.com/8iQsxPSWQ4H92bq
> >
> > Bug: 1481745
> > Change-Id: Idb432fe1b168dd4a0f2090e2af7c1cbd741900ba
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4860441
> > Reviewed-by: Theresa Sullivan <twellington@chromium.org>
> > Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> > Commit-Queue: Yaron Friedman <yfriedman@chromium.org>
> > Auto-Submit: Wenyu Fu <wenyufu@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1195762}
>
> Bug: 1481745
> Change-Id: Ifc3b76b61c60764c9aee180c90d1c2bdf9c2e26d
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4861822
> Owners-Override: Fergal Daly <fergal@google.com>
> Owners-Override: Takuto Ikuta <tikuta@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Kalvin Lee <kdlee@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1195803}

Bug: 1481745
Change-Id: I653471b1780205ea8e5aece811d9306faa5a45d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4863038
Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
Commit-Queue: Wenyu Fu <wenyufu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1196181}
NOKEYCHECK=True
GitOrigin-RevId: 026a38058e5c10b507b6ca92b01f76f0a582ccac