Fix typo in fetch_all.py
Typo was causing script to fail with:
TypeError: __init__() got an unexpected keyword argument 'actino'

Change-Id: I9ea784032a5a5a5e4fe7659804d797db799068f6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1707171
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#678517}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 99399481b7bcc2737e8902185f0f3225caf95704