Revert "[Settings] Add settings file name presubmit"
This reverts commit 5097e3556e89bc457880a5f6a5fe22426cf0ffaf.

Reason for revert: PRESUBMIT fails:

```
Running Python 3 presubmit upload checks ...
  18.1s to run CheckUnwantedDependencies from /usr/local/google/home/kdlee/chromium/src/PRESUBMIT.py.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The value of attribute "value" associated with an element type "property" must not contain the '<' character.:226:57
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:321)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:266)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:380)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: org.xml.sax.SAXParseException; systemId: file:/usr/local/google/home/kdlee/chromium/src/tools/android/checkstyle/chromium-style-5.0.xml; lineNumber: 226; columnNumber: 57; The value of attribute "value" associated with an element type "property" must not contain the '<' character.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:943)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1522)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:81)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:315)
        ... 5 more
Checkstyle ends with 1 errors.
```

Original change's description:
> [Settings] Add settings file name presubmit
>
> Prevent new class added with suffix "PreferenceFragment". Regex tested through https://screenshot.googleplex.com/8iQsxPSWQ4H92bq
>
> Bug: 1481745
> Change-Id: Idb432fe1b168dd4a0f2090e2af7c1cbd741900ba
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4860441
> Reviewed-by: Theresa Sullivan <twellington@chromium.org>
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Commit-Queue: Yaron Friedman <yfriedman@chromium.org>
> Auto-Submit: Wenyu Fu <wenyufu@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1195762}

Bug: 1481745
Change-Id: Ifc3b76b61c60764c9aee180c90d1c2bdf9c2e26d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4861822
Owners-Override: Fergal Daly <fergal@google.com>
Owners-Override: Takuto Ikuta <tikuta@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1195803}
NOKEYCHECK=True
GitOrigin-RevId: 595272f36e94f0efc4916ca6e1a7fa7c978b9539